plugin: remove unused variable
Fixes compilation with gcc 4.6.

 gstomx.c:241:35: error: variable 'component_role' set but not used [-Werror=unused-but-set-variable]

Signed-off-by: Felipe Contreras <felipe.contreras@nokia.com>